import {
  DumbbellIcon,
  SunIcon,
  GraduationCapIcon,
  UsersIcon,
  BusIcon,
  WifiIcon,
  LanguagesIcon,
  BookOpenIcon,
  PresentationIcon,
  UtensilsIcon,
  LeafIcon,
  SofaIcon,
  BeanIcon,
  LibraryBig,
  WavesLadderIcon,
  AccessibilityIcon,
  Building2Icon,
  HeartPulseIcon,
  LaptopIcon,
  SchoolIcon,
  ShieldCheckIcon,
  ShieldIcon,
  DropletIcon,
  ArrowUpDownIcon,
  MonitorIcon,
  FlaskConicalIcon,
  MicIcon,
  WrenchIcon,
  FolderKanbanIcon,
  FileTextIcon,
  LandmarkIcon,
  BriefcaseIcon,
  ConciergeBellIcon,
  BookAIcon,
  LandPlotIcon,
  TreesIcon,
  LockIcon,
  ClipboardListIcon,
  TrophyIcon,
  PackageCheckIcon,
  DicesIcon,
  FlowerIcon,
  AwardIcon,
  UserCircleIcon,
  AmbulanceIcon,
  PhoneCallIcon,
  BriefcaseMedicalIcon,
  StethoscopeIcon,
  DrumstickIcon,
  ChefHatIcon,
  StoreIcon,
  MonitorSmartphoneIcon,
  ParkingCircleIcon,
  CarIcon,
  MapPinIcon,
  BikeIcon,
  ZapIcon,
  TruckIcon,
  CalendarDaysIcon,
  UserRoundIcon,
  FlagIcon,
  DramaIcon,
  CameraIcon,
  FlameIcon,
  DoorOpenIcon,
  SirenIcon,
  ShieldUserIcon,
} from "lucide-react";

export type AmenityOption = { name: string; options: string[] };
export type AmenityItem = string | AmenityOption;

export type AmenitiesType = {
  [category: string]: AmenityItem[];
};
export const CategoryIcons: Record<string, any> = {
  Mandatory: SunIcon,
  "Basic Facilities": Building2Icon,
  "Academic Facilities": BookOpenIcon,
  "Common Area": GraduationCapIcon,
  "Sports & Recreation": DumbbellIcon,
  "Health & Medical": HeartPulseIcon,
  "Food & Dining": UtensilsIcon,
  "Technology & Digital": LaptopIcon,
  "Campus Infrastructure": SchoolIcon,
  Transportation: BusIcon,
  "Student Life & Community": UsersIcon,
  security: ShieldUserIcon,
};
export const SubcategoryIcons: Record<string, any> = {
  // Mandatory
  "Ragging-Free Campus": ShieldCheckIcon,
  "24x7 Security": ShieldIcon,
  WiFi: WifiIcon,
  "Drinking Water (RO)": DropletIcon,
  "Wheelchair Accessibility": AccessibilityIcon,
  "Elevator / Lift": ArrowUpDownIcon,

  // Basic Facilities
  Classrooms: SchoolIcon,
  "ATM / Banking Facility": LandmarkIcon,

  //Academic Facilities
  "Computer Lab": MonitorIcon,
  "Science Labs": FlaskConicalIcon,
  "Workshops & Training Rooms": WrenchIcon,
  "Project Rooms": FolderKanbanIcon,
  "Exam Hall": FileTextIcon,
  "Doubt Solving Sessions": BookOpenIcon,
  "Soft Skills & Communication Training": LanguagesIcon,
  "Placement Training": BriefcaseIcon,
  Auditorium: MicIcon,

  //Common Area
  Reception: ConciergeBellIcon,
  "Waiting Lounge": SofaIcon,
  "Conference Rooms": PresentationIcon,
  Garden: BeanIcon,
  Library: LibraryBig,
  "Study Rooms": BookAIcon,
  "Playground / Assembly Ground": LandPlotIcon,
  "Terrace Sitting Area": TreesIcon,
  "Locker Areas": LockIcon,
  "Notice Board / Result Display Area": ClipboardListIcon,

  //Sports & Recreation
  "Annual Sports Day": TrophyIcon,
  "Sports Ground": LandPlotIcon,
  "Indoor Sports Area": DicesIcon,
  "Sports Equipment Availability": PackageCheckIcon,
  "Gym / Fitness Center": DumbbellIcon,
  "Yoga / Meditation Room": FlowerIcon,
  "Swimming Pool": WavesLadderIcon,
  "Professional Coaches / Trainers": UserCircleIcon,
  "Inter-school / Inter-college Competitions": AwardIcon,

  //Health & Medical
  "Medical Room": StethoscopeIcon,
  "First Aid Kit": BriefcaseMedicalIcon,
  "Doctor on Call": PhoneCallIcon,
  "Ambulance Service": AmbulanceIcon,
  "Health Check-up Camps": HeartPulseIcon,

  //food and dining
  "Canteen / Cafeteria": UtensilsIcon,
  "Food Court": StoreIcon,
  "Mess Facility": ChefHatIcon,
  "Vegetarian Options": LeafIcon,
  "Non-Vegetarian Options": DrumstickIcon,

  //Technology & Digital
  "Online Learning Support": LaptopIcon,
  "Projector Rooms": PresentationIcon,
  "Smart Boards": MonitorSmartphoneIcon,

  //Transportations
  Parking: ParkingCircleIcon,
  "College Bus Service": BusIcon,
  "Pickup & Drop Facility": CarIcon,
  "Transport Assistance Desk": MapPinIcon,
  "Bicycle Stand": BikeIcon,
  "EV Charging Point": ZapIcon,
  "E-Rickshaw / Golf Cart Transport": TruckIcon,

  //Student Life and Community
  "Clubs & Societies": UsersIcon,
  "Drama Club": DramaIcon,
  "NSS / NCC": FlagIcon,
  "Student Union": UserRoundIcon,
  "Workshops & Events": CalendarDaysIcon,
  "Internship Cell": BriefcaseIcon,

  //security
  "Security Guard": ShieldIcon,
  "CCTV Surveillance": CameraIcon,
  "Fire Safety Measures": FlameIcon,
  "Emergency Exit Plan": DoorOpenIcon,
  "Panic Button / Emergency Alert System": SirenIcon,
};
