export const originalTestimonials = [
	{
		id: 1,
		name: "Aarav Patel",
		role: "Engineering Aspirant",
		date: "12 Oct, 2023",
		rating: 5.0,
		image: "/img/testimonials/user-1.webp",
		text: "Shortlisting colleges after Class 12 was overwhelming. Campusaim helped me compare colleges, courses, and eligibility criteria in one place, which saved me a lot of time and confusion.",
	},
	{
		id: 2,
		name: "Sarah Jenkins",
		role: "International Student",
		date: "05 Nov, 2023",
		rating: 5.0,
		image: "/img/testimonials/user-2.webp",
		text: "As an international student, understanding admission requirements was challenging. Campusaim made it easier to explore universities and course options with clear, structured information.",
	},
	{
		id: 3,
		name: "Dr. Kavita Sharma",
		role: "Academic Counselor",
		date: "22 Jan, 2024",
		rating: 5.0,
		image: "/img/testimonials/user-3.webp",
		text: "I recommend Campusaim to students who need clarity while researching colleges. The platform presents academic data in a simple and reliable format that supports informed decision-making.",
	},
	{
		id: 4,
		name: "Michael Ross",
		role: "Postgraduate Applicant",
		date: "14 Feb, 2024",
		rating: 5.0,
		image: "/img/testimonials/user-4.webp",
		text: "I was searching for universities offering accredited postgraduate programs. Campusaim provided accurate course details and helped me shortlist institutions aligned with my academic background.",
	},
	{
		id: 5,
		name: "Priya Desai",
		role: "Parent",
		date: "30 Mar, 2024",
		rating: 5.0,
		image: "/img/testimonials/user-5.webp",
		text: "As a parent, transparency matters. Campusaim helped us understand fees, eligibility, and course options clearly, making college selection more confident and stress-free.",
	},
	{
		id: 6,
		name: "Liam O'Connor",
		role: "MBA Aspirant",
		date: "10 Apr, 2024",
		rating: 5.0,
		image: "/img/testimonials/user-6.webp",
		text: "Comparing management colleges manually was time-consuming. Campusaim’s structured listings and filters helped me narrow down options based on location, fees, and entrance exams.",
	},
	{
		id: 7,
		name: "Meera Reddy",
		role: "Final-Year Undergraduate Student",
		date: "18 May, 2024",
		rating: 5.0,
		image: "/img/testimonials/user-7.webp",
		text: "Campusaim helped me explore postgraduate courses and understand admission requirements clearly. It’s a reliable starting point for students planning their next academic step.",
	},
];
