export const originalTestimonials = [
  {
    id: 1,
    name: "Aarav Patel",
    role: "Yoga Practitioner",
    date: "12 Oct, 2023",
    rating: 5.0,
    image: "/img/testimonials/user-1.webp",
    text: "Finding a genuine yoga studio in a new city can be daunting. YogPrerna verified listings gave me the confidence to book my monthly pass without visiting first. The comparison tool is a lifesaver!",
  },
  {
    id: 2,
    name: "Sarah Jenkins",
    role: "Studio Owner",
    date: "05 Nov, 2023",
    rating: 5.0,
    image: "/img/testimonials/user-2.webp",
    text: "Since listing 'Tranquil Flows' on YogPrerna, our student inquiries have increased by 40%. It is the only platform that truly understands the spiritual ecosystem and connects us with serious seekers.",
  },
  {
    id: 3,
    name: "Dr. Kavita Sharma",
    role: "Ayurveda Specialist",
    date: "22 Jan, 2024",
    rating: 5.0,
    image: "/img/testimonials/user-3.webp",
    text: "I used the Q&A forum to discuss therapeutic yoga techniques, and the community quality is outstanding. YogPrerna has built a trustworthy environment for professionals and students alike.",
  },
  {
    id: 4,
    name: "Michael Ross",
    role: "YTT Student",
    date: "14 Feb, 2024",
    rating: 5.0,
    image: "/img/testimonials/user-4.webp",
    text: "I was looking for a university offering a formal degree in Yogic Sciences. YogPrerna was the only site with accurate, detailed data on colleges and curriculums. Highly recommended for academic research.",
  },
  {
    id: 5,
    name: "Priya Desai",
    role: "Event Organizer",
    date: "30 Mar, 2024",
    rating: 5.0,
    image: "/img/testimonials/user-5.webp",
    text: "Promoting our annual Wellness Retreat on YogPrerna was seamless. The audience here is exactly who we want to reach. The platform's trust factor definitely helped us sell out our early bird tickets.",
  },
  {
    id: 6,
    name: "Liam O'Connor",
    role: "Wellness Traveler",
    date: "10 Apr, 2024",
    rating: 5.0,
    image: "/img/testimonials/user-6.webp",
    text: "The detailed property comparisons helped me choose the perfect ashram for my sabbatical. YogPrerna.com takes the guesswork out of finding authentic spiritual environments.",
  },
  {
    id: 7,
    name: "Meera Reddy",
    role: "Hatha Yoga Instructor",
    date: "18 May, 2024",
    rating: 5.0,
    image: "/img/testimonials/user-7.webp",
    text: "As a freelancer, credibility is everything. Having a verified profile on YogPrerna has helped me build trust with new clients instantly. It is the gold standard for yoga professionals.",
  },
];
