type AmenityOption = { name: string; options: string[] };
type AmenityItem = string | AmenityOption;
type AmenitiesType = {
  [category: string]: AmenityItem[];
};

export const AmenitiesData: AmenitiesType = {
  Mandatory: [
    "Air Conditioning",
    { name: "Laundry", options: ["Free", "Paid"] },
    "Newspaper",
    "Televison",
    "Mobile Service",
    "Fire Safety Measures",
    "CCTV Surveillance",
    "First Aid Kit",
    "24x7 Power Supply",
  ],
  "Basic Facilities": [
    { name: "WiFi", options: ["Free", "Paid"] },
    "Power Backup",
    "Wheelchair Accessibility",
    "Daily Housekeeping",
    "Elevator / Lift",
  ],
  "General Services": [
    { name: "Room Service", options: ["Free", "Paid"] },
    "Security",
    "Reception",
    "Sitting Area",
    "Luggage Storage",
    { name: "Language Support / Translator", options: ["Free", "Paid"] },
    "Maintenance Support",
    "Lost and Found Desk",
  ],
  "Yoga Facilities": [
    "Meditation Hall",
    "Open-Air Yoga Space",
    "Indoor Yoga Studio",
    "Sound Healing Room",
    "Props (Blocks, Straps, Bolsters)",
    "Silent Meditation Rooms",
    "Library",
    "Instructor-Led Sessions",
    "Sunrise Yoga",
    "Pranayama Sessions",
    "Ayurvedic Therapy Room",
    "Detox & Cleansing Programs",
    "Wellness Consultation Desk",
    "Mindfulness Workshops",
    "Chanting & Mantra Sessions",
    "Yoga Philosophy Lectures",
    "Nature Meditation Retreats",
  ],
  "Common Area": [
    "Lounge",
    "Terrace",
    "Garden",
    "Courtyard",
    "Amphitheatre",
    "Community Hall",
    "Study & Discussion Zone",
  ],
  "Outdoor & Recreational": [
    "Walking Trails",
    "Nearby Nature Spots",
    "Cultural Activities",
    "Swimming Pool",
    "Gym",
    "Nature Walks",
    "Outdoor Meditation Platforms",
    "Bonfire or Cultural Evenings",
    "Sports Grounds",
    "Cycling Tracks",
    "Outdoor Class Area",
    "Organic Farming Zone",
    "Eco-Garden",
  ],
  "Food and Drink": [
    "Restaurant",
    "Cafe",
    "Community Dining Area",
    "Meals Provided",
    "Herbal Tea Station",
    "Organic / Sattvic Food Options",
    "Juice & Smoothie Bar",
  ],
  Transportation: [
    { name: "Parking", options: ["Indoor", "Outdoor"] },
    "Pickup & Drop Service",
    "Shuttle to Nearby Attractions",
    { name: "Bicycle Rental", options: ["Free", "Paid"] },
    "Local Sightseeing Tours",
    "Public Transport Assistance",
    "Campus Shuttle",
  ],
  "Academic & Learning Facilities": [
    "Classrooms",
    "Lecture Halls",
    "Workshops & Seminar Rooms",
    "Computer Lab",
    "Library with Research Section",
    "Study Lounges",
    "Academic Counseling Desk",
    "Online Learning Facilities",
  ],
  "Health & Wellness": [
    "Ayurvedic Center",
    "Herbal Garden",
    "On-Campus Clinic",
    "Doctor on Call",
    "Therapy Rooms",
    "Massage & Spa Facilities",
    "Health Check-up Camps",
  ],
  "Student Life & Community": [
    "Hostel Accommodation",
    "Common Kitchen",
    "Cultural Club",
    "Yoga Student Union",
    "Meditation Groups",
    "Workshops & Retreat Programs",
    "Volunteering Opportunities",
  ],
};
